### ISSUE TITLE
manifest generator path issues on Windows

### ISSUE THREAD

**Issue by nickpankow** [hotwired-laravel/stimulus-laravel#14]
Hello!

Generating manifests using a command like `php artisan stimulus:make hello_controller` creates an unbuildable manifest if run on a Windows machine.

Performing the following on brand new Laravel project:
1. `composer require hotwired-laravel/stimulus-laravel`
2. `php artisan stimulus:install`
3. `php artisan stimulus:make hello_controller`

The outputted js/controllers/index.js file is unbuildable and looks like so:
```js
// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { application } from '../libs/stimulus'


import C:__Users__Nickp__Documents__Test__Laravel__Resources__Js__Controllers__HelloController from '.\C:\Users\nickp\Documents\test\laravel\resources\js\controllers\hello_controller'
application.register('C:--Users--nickp--Documents--test--laravel--resources--js--controllers--hello', C:__Users__Nickp__Documents__Test__Laravel__Resources__Js__Controllers__HelloController)
```

Performing the same sequence on a Macbook works and builds great!

If I am not doing something silly or if there is not a reasonable workaround, I would be happy to put together a pull request.

Thanks for your work on this project!

**Comment by tonysm** [comment]
Hey. Thanks for reporting it. Unfortunately, I don't have an easy way to test it on Windows. I'll set up a VM over the weekend if I have some spare time. In the meantime, you can give it a try. It should be straightforward to debug it. The manifest is generated in the `Manifest` class ([here](https://github.com/hotwired-laravel/stimulus-laravel/blob/a605e4706758533bdaa787706d0696afec531e39/src/Manifest.php#L14-L35)), and there's a test for it [here](https://github.com/hotwired-laravel/stimulus-laravel/blob/a605e4706758533bdaa787706d0696afec531e39/tests/ManifestTest.php#L10). It's already using `DIRECTORY_SEPARATOR` and the tests are running on [windows in CI](https://github.com/hotwired-laravel/stimulus-laravel/blob/a605e4706758533bdaa787706d0696afec531e39/.github/workflows/run-tests.yml#L15), so it must be something weird going on there.

**Comment by nickpankow** [comment]
I was able to replicate the issue today on one of our Windows Server 2016 VMs with a fresh project.  I'll dive in and work on a PR over the next few days.  Probably something strange with the path differences with Windows.

**Comment by tonysm** [comment]
@nickpankow I was able to set up a VM tonight and found a solution! Should be sending a PR soon

**Comment by tonysm** [comment]
Tagged version [0.3.1](https://github.com/hotwired-laravel/stimulus-laravel/releases/tag/0.3.1) with the fix. Thanks @nickpankow for reporting it and taking a look!

**Comment by nickpankow** [comment]
> Tagged version [0.3.1](https://github.com/hotwired-laravel/stimulus-laravel/releases/tag/0.3.1) with the fix. Thanks @nickpankow for reporting it and taking a look!

works great - thank you!
